apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: space
spec:
  exporter:
    endpoint: http://space-collector:4318
  env:
  propagators:
    - tracecontext
    - baggage
