apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: space
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      debug:
      otlp:
        endpoint: "api.honeycomb.io:443" # US instance
        headers:
          "x-honeycomb-team": "${OTEL_HONEYCOMB_APIKEY}"
      otlp/metrics:
        endpoint: api.honeycomb.io:443
        headers:
          "x-honeycomb-team": "${OTEL_HONEYCOMB_APIKEY}"
          x-honeycomb-dataset: space-metrics

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp]
  env:
    - name: OTEL_HONEYCOMB_APIKEY
      valueFrom:
        secretKeyRef:
          name: otel-honeycomb-apikey
          key: apikey